apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-authserver
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: pasientskyhosting/kubernetes-authserver:latest
        ports:
        - containerPort: 8087
      - image: gcr.io/google_containers/addon-resizer:1.7
        name: authserver-nanny
        resources:
          limits:
            cpu: 50m
            memory: 90Mi
          requests:
            cpu: 50m
            memory: 90Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --cpu=200m
          - --extra-cpu=60m
          - --memory=200Mi
          - --extra-memory=6Mi
          - --threshold=5
          - --deployment=kubernetes-authserver
          - --container=authserver
          - --poll-period=300000
          - --estimator=exponential