apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-authserver
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: pasientskyhosting/kubernetes-authserver:latest
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        env:
          - name: DB_HOST
            value: "10.50.41.11"

          - name: DB_PORT
            value: "3306"

          - name: DB_USER
            value: "auth"

          - name: DB_PASS
            value: "bananskal"

          - name: DB_NAME
            value: "auth"
        ports:
          - containerPort: 8087

      - name: authserver-nanny
        image: gcr.io/google_containers/addon-resizer:1.7
        resources:
          limits:
            cpu: 50m
            memory: 90Mi
          requests:
            cpu: 50m
            memory: 90Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --cpu=200m
          - --extra-cpu=60m
          - --memory=200Mi
          - --extra-memory=6Mi
          - --threshold=5
          - --deployment=kubernetes-authserver
          - --container=authserver
          - --poll-period=300000
          - --estimator=exponential